name: ib_points_calc
description: IB score calculator for normal subjects

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animator: ^1.0.0+1
  cupertino_icons: ^0.1.2
  material_design_icons_flutter: ^3.2.3895
  shared_preferences: ^0.5.4+3
  autocomplete_textfield: ^1.6.4
  cloud_firestore: ^0.13.0+1
  firebase_core: 0.4.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.3

flutter_icons:
  image_path: "assets/icon.png"
  android: true
  ios: true


flutter:
  uses-material-design: true